sudo: required
language: python
services:
  - docker
before_script:
  - docker build -t ricordanza/japanize ubuntu/japanize/.
  - docker build -t ricordanza/develop ubuntu/develop/.
  - docker build -t ricordanza/python ubuntu/python/.
  - docker build -t ricordanza/lambda ubuntu/lambda/.
  - docker build -t ricordanza/centos7-japanize centos7/japanize/.
  - docker build -t ricordanza/go ubuntu/go/.
  - docker build -t ricordanza/node ubuntu/node/.
  - docker build -t ricordanza/ruby ubuntu/ruby/.
  - docker build -t ricordanza/serverless ubuntu/serverless/.
  - docker build -t ricordanza/dlfs other/dlfs/.
  - docker build -t ricordanza/centos7-php56 centos7/php56/.
  - docker build -t ricordanza/aws ubuntu/aws/.
  - docker build -t ricordanza/severspec ubuntu/serverspec/.
  - docker build -t ricordanza/heroku ubuntu/heroku/.
  - docker build -t ricordanza/terraform ubuntu/terraform/.
script:
  - docker run ricordanza/japanize bash
